name: imagePRlevel

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      commitSHA:
        description: "pr commit SHA"
        required: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  image_build_for_specific_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        ref: ${{ github.event.inputs.commitSHA }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tiwatsuka/kepler
          labels: ${{ github.event.inputs.commitSHA }}
          file: build/Dockerfile.libbpf.kepler
